//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forte7000E.Module.SerialCom.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ScaleCommIndex {
            get {
                return ((int)(this["ScaleCommIndex"]));
            }
            set {
                this["ScaleCommIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ScaleBaudRateIndex {
            get {
                return ((int)(this["ScaleBaudRateIndex"]));
            }
            set {
                this["ScaleBaudRateIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ScaleParityIndex {
            get {
                return ((int)(this["ScaleParityIndex"]));
            }
            set {
                this["ScaleParityIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ScaleDataBitIndex {
            get {
                return ((int)(this["ScaleDataBitIndex"]));
            }
            set {
                this["ScaleDataBitIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ScaleStopBitIndex {
            get {
                return ((int)(this["ScaleStopBitIndex"]));
            }
            set {
                this["ScaleStopBitIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bSimWtRandom {
            get {
                return ((bool)(this["bSimWtRandom"]));
            }
            set {
                this["bSimWtRandom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ScaleModeIndex {
            get {
                return ((int)(this["ScaleModeIndex"]));
            }
            set {
                this["ScaleModeIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StrWeightReq {
            get {
                return ((string)(this["StrWeightReq"]));
            }
            set {
                this["StrWeightReq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P")]
        public string ScaleCharReq {
            get {
                return ((string)(this["ScaleCharReq"]));
            }
            set {
                this["ScaleCharReq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int idxStrCharOne {
            get {
                return ((int)(this["idxStrCharOne"]));
            }
            set {
                this["idxStrCharOne"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int idxStrCharTwo {
            get {
                return ((int)(this["idxStrCharTwo"]));
            }
            set {
                this["idxStrCharTwo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int idxStrCharThree {
            get {
                return ((int)(this["idxStrCharThree"]));
            }
            set {
                this["idxStrCharThree"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int idxEndCharOne {
            get {
                return ((int)(this["idxEndCharOne"]));
            }
            set {
                this["idxEndCharOne"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int idxEndCharTwo {
            get {
                return ((int)(this["idxEndCharTwo"]));
            }
            set {
                this["idxEndCharTwo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int idxEndCharThree {
            get {
                return ((int)(this["idxEndCharThree"]));
            }
            set {
                this["idxEndCharThree"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double strSimWeight {
            get {
                return ((double)(this["strSimWeight"]));
            }
            set {
                this["strSimWeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OscCommIndex {
            get {
                return ((int)(this["OscCommIndex"]));
            }
            set {
                this["OscCommIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OscBaudRateIndex {
            get {
                return ((int)(this["OscBaudRateIndex"]));
            }
            set {
                this["OscBaudRateIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OscParityIndex {
            get {
                return ((int)(this["OscParityIndex"]));
            }
            set {
                this["OscParityIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OscDataBitIndex {
            get {
                return ((int)(this["OscDataBitIndex"]));
            }
            set {
                this["OscDataBitIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OscStopBitIndex {
            get {
                return ((int)(this["OscStopBitIndex"]));
            }
            set {
                this["OscStopBitIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OscModeIndex {
            get {
                return ((int)(this["OscModeIndex"]));
            }
            set {
                this["OscModeIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OscMode {
            get {
                return ((string)(this["OscMode"]));
            }
            set {
                this["OscMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int iForteRange {
            get {
                return ((int)(this["iForteRange"]));
            }
            set {
                this["iForteRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bOscRandom {
            get {
                return ((bool)(this["bOscRandom"]));
            }
            set {
                this["bOscRandom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectS1PortIndex {
            get {
                return ((int)(this["SelectS1PortIndex"]));
            }
            set {
                this["SelectS1PortIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectS1BaudRateIndex {
            get {
                return ((int)(this["SelectS1BaudRateIndex"]));
            }
            set {
                this["SelectS1BaudRateIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectS1ParityIndex {
            get {
                return ((int)(this["SelectS1ParityIndex"]));
            }
            set {
                this["SelectS1ParityIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectS1StopBitIndex {
            get {
                return ((int)(this["SelectS1StopBitIndex"]));
            }
            set {
                this["SelectS1StopBitIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectS1DataIndex {
            get {
                return ((int)(this["SelectS1DataIndex"]));
            }
            set {
                this["SelectS1DataIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SerialOneCommIndex {
            get {
                return ((int)(this["SerialOneCommIndex"]));
            }
            set {
                this["SerialOneCommIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SerialOneBaudRateIndex {
            get {
                return ((int)(this["SerialOneBaudRateIndex"]));
            }
            set {
                this["SerialOneBaudRateIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SerialOneParityIndex {
            get {
                return ((int)(this["SerialOneParityIndex"]));
            }
            set {
                this["SerialOneParityIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SerialOneDataBitIndex {
            get {
                return ((int)(this["SerialOneDataBitIndex"]));
            }
            set {
                this["SerialOneDataBitIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SerialOneStopBitIndex {
            get {
                return ((int)(this["SerialOneStopBitIndex"]));
            }
            set {
                this["SerialOneStopBitIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SerialOneEnable {
            get {
                return ((bool)(this["SerialOneEnable"]));
            }
            set {
                this["SerialOneEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int ScaleRetryPeriod {
            get {
                return ((int)(this["ScaleRetryPeriod"]));
            }
            set {
                this["ScaleRetryPeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ScaleRetry {
            get {
                return ((int)(this["ScaleRetry"]));
            }
            set {
                this["ScaleRetry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int OscRetryPeriod {
            get {
                return ((int)(this["OscRetryPeriod"]));
            }
            set {
                this["OscRetryPeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int OscRetry {
            get {
                return ((int)(this["OscRetry"]));
            }
            set {
                this["OscRetry"] = value;
            }
        }
    }
}
